from time import *
print("Starting Setup...")
sleep(.54)
from os import *
system("clear")
system("apt install python3")
system("clear")
system("pip3 install requests")
system("pip3 install bs4")
system("clear")
system("chmod +x *")
system("cp webScrap ../../usr/bin")
system("cd ../../usr/bin")
system("chmod +x webScrap")
system("cd $HOME")
system("cd webScrap")
system("cp recursiveScrap ../../usr/bin")
system("cd ../../usr/bin")
system("chmod +x recursiveScrap")
system("cd $HOME")
print("Now Type webScrap -h To Get Help Menu")