#!/data/data/com.termux/files/usr/bin/python3
from os import *
from sys import *
green="\033[1;32;40m"
red="\033[1;31;40m"
drk="\033[1;30;40m"
white="\033[1;37;40m"
usage=f"{red}[?] Arguments Missing [?]\n\n{green}Usage : {white}python3 webScrap.py url\n\n{red}Example : {white}python3 webScrap.py https://www.example.com"
if (len(argv) != 2):         print(usage)         exit(0)
try:         from bs4 import *
except:         print(f"{red} bs4 Module Not Found !!! \nNow Installing...")         system('pip3 install bs4')         system('clear')         print(f"{white}Now Restart Program")         exit(0)
import threading
try:         from requests import *
except:         print(f"{red} Requests Module Not Found !!! \nNow Installing...")         system('pip3 install requests')         system('clear')         print(f"{white}Now Restart Program")         exit(0)
ur=argv[1]
url=get(ur)
cont=url.content
soup=BeautifulSoup(cont,'html.parser')
anc = soup.find_all('a')
#print(anc.string)
all_links = set()
def full(link):         if link.get('href')!="#":                 if 'http' not in link.get('href'):                         link1 = f"https://{ur}{link.get('href')}"                         all_links.add(link1)                 else:                         all_links.add(link.get('href'))
for link in anc:         thread= threading.Thread(target=full,args=(link,))         thread.start()
final=list(all_links)
final='\n'.join(final)
print(f"{green}{final}")
